site_name: 李占兵的博客
site_url: https://zhanbingli.github.io
site_author: 李占兵
site_description: 个人知识分享与技术博客

# Repository
repo_name: zhanbingli/zhanbingli.github.io
repo_url: https://github.com/zhanbingli/zhanbingli.github.io

# Copyright
copyright: Copyright &copy; 2024 李占兵

# Configuration
theme:
  name: material
  language: zh
  palette:
    # 亮色模式
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: 切换到暗色模式
    # 暗色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: 切换到亮色模式
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.suggest
    - content.code.copy  # 代码复制按钮
    - content.code.annotate  # 代码注释功能
  favicon: assets/favicon.svg
  icon:
    logo: material/library

# 内容设置
docs_dir: docs
use_directory_urls: true

# Plugins
plugins:
  - search:
      lang: zh
  - minify:  # 压缩输出文件
      minify_html: true

# Markdown扩展
markdown_extensions:
  - pymdownx.highlight:  # 代码高亮
      anchor_linenums: true
  - pymdownx.superfences  # 高级代码围栏
  - pymdownx.tabbed  # 标签页
  - pymdownx.tasklist:  # 任务列表
      custom_checkbox: true
  - admonition  # 提示块
  - footnotes  # 脚注
  - attr_list  # 属性列表
  - tables  # 表格

# 样式表
extra_css:
  - stylesheets/extra.css

# Page tree
nav:
  - 首页: index.md
  - 技术博客: 
    - Python异步编程: tech/python-异步编程实践.md
    - 如何写博客文章: tech/how-to-write-blog.md
  - 生活随笔: 
    - 旅行笔记: life/travel-notes.md
  - 关于我: about.md
