site_name: 李占兵的博客
site_url: https://zhanbingli.github.io
site_author: 李占兵
site_description: 个人知识分享与技术博客

# Repository
repo_name: zhanbingli/zhanbingli.github.io
repo_url: https://github.com/zhanbingli/zhanbingli.github.io

# Copyright
copyright: Copyright &copy; 2024 李占兵

# Configuration
theme:
  name: material
  language: zh
  palette:
    # 亮色模式
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: 切换到暗色模式
    # 暗色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: 切换到亮色模式
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - search.suggest
  favicon: assets/favicon.svg
  icon:
    logo: material/library

# 内容设置
docs_dir: docs
use_directory_urls: true

# Plugins
plugins:
  - search

# Page tree
nav:
  - 首页: index.md
  - 技术博客: 
    - 技术首页: tech/index.md
    - Python异步编程: tech/python-异步编程实践.md
    - 如何写博客文章: tech/how-to-write-blog.md
  - 生活随笔: 
    - 生活首页: life/index.md
    - 旅行笔记: life/travel-notes.md
  - 关于我: about.md
