site_name: 我留在世界上的痕迹
site_url: https://zhanbingli.github.io/
site_author: 李占兵
site_description: 个人知识分享与技术博客

# Repository
repo_name: zhanbingli/zhanbingli.github.io
repo_url: https://github.com/zhanbingli/zhanbingli.github.io

# Copyright
copyright: Copyright &copy; 2025 李占兵

# Configuration
theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - navigation.sections
    - navigation.tracking
    - header.autohide
    - search.suggest
    - search.highlight
    - content.tabs.link
    - toc.follow
    - toc.integrate
    - content.code.copy
    - content.action.edit
    - navigation.footer
    - navigation.top
    - toc.follow
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切换到暗色模式
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 切换到亮色模式
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: material/book-open-page-variant
  extra_css:
    - stylesheets/extra.css
  extra_javascript:
    - javascripts/extra.js
  custom_dir: theme

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
  - tags
  - blog:
      blog_dir: blog
      post_dir: "{blog}/posts"
      archive: true
      categories: true
      pagination: true
      pagination_per_page: 5
      authors_file: "{blog}/.authors.yml"
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Zhanbingli
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/zhanbingli
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/zhanbingli
  analytics:
    provider: google
    property: G-XXXXXXXXXX
  # 启用 Disqus 评论系统
  disqus: zhanbingli
  # 启用社交分享
  social_share:
    - platform: twitter
    - platform: facebook
    - platform: linkedin
    - platform: weibo
  consent:
    title: Cookie 同意
    description: >-
      我们使用 cookies 来识别您的重复访问和偏好，以及
      测量我们文档的有效性以及用户是否找到他们要找的内容。
      在您的同意下，您正在帮助我们改进我们的网站。
    actions:
      - accept
      - reject
      - manage
  feedback:
    title: 这个页面有帮助吗？
    ratings:
      - icon: material/emoticon-happy-outline
        name: 这个页面有帮助
        data: 1
        note: >-
          感谢您的反馈！
      - icon: material/emoticon-sad-outline
        name: 这个页面需要改进
        data: 0
        note: >- 
          感谢您的反馈！请告诉我们如何改进。
  authors:
    zhanbingli:
      name: 李占兵
      description: 网站作者

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

# Page tree
nav:
  - 首页: index.md
  - 博客:
    - blog/index.md
  - 技术博客: 
    - 技术首页: tech/index.md
    - Python异步编程: tech/python-异步编程实践.md
    - Markdown指南: tech/markdown-guide.md
  - 生活随笔: 
    - 生活首页: life/index.md
    - 旅行笔记: life/travel-notes.md
  - 英语学习: english/index.md
  - 关于我: about.md
  - 标签: tags.md
